# Base configs
url: "https://gallery.digitalden.cloud"
baseurl: ""   # leave empty when using a custom domain

image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Deniz Yilmaz"
subtitle: "See the world through my eyes!"
author: "Deniz Yilmaz"
header:
 title: "Photography"
 subtitle: "by Deniz Yilmaz"
footer:
 name: "Hey there, my name is Deniz"
 bio: "Coming Soon"
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/rampatra/photography\">fork this repo on github</a> ;)"
web_design: "AJ"

social_urls:
  linkedin: "https://www.linkedin.com/in/digitalden/"
  github: "https://www.github.com/DigitalDenCloud"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'